### PR TITLE
Fix path encoding

### LINKED ISSUE #28: Regression in version 1.2
A bug slipped through the tests in to the release. From a quick glance I think it is about empty paths.

`Uninitialized string offset: 0 in imgix/imgix-php/src/Imgix/UrlHelper.php at 25`

### PR DESCRIPTION
**Pull request by jayeb**
This PR fixes the path-encoding logic for this library, to bring it in line with other libraries in our SDK. The logic is as follows:

- **All paths are expected to be passed in unencoded.** If a path is provided that is already encoded, it will become double-encoded.
- **If the path matches `/^https?:\/\//`, it will be fully encoded, slashes and all.** In this case, we're assuming it's a fully-qualified URL (this is necessary for [web proxy sources](https://docs.imgix.com/setup/creating-sources/web-proxy)). We had previously been using `urlencode()` for this, but [version 1.2.0](https://github.com/imgix/imgix-php/releases/tag/1.2.0) introduced an option to use `rawurlencode()` instead. This PR removes that option and uses `rawurlencode()` in all cases. The general consensus in the PHP community seems to be that `rawurlencode()` is strictly better for our use-case--see [this SO thread](https://stackoverflow.com/questions/996139/urlencode-vs-rawurlencode) for more info.
- **If the path does not match `/^https?:\/\//`, it will be partially-encoded**. Non-URL-safe characters (everything that matches `/([^\w\-\/\:@])/`) will be encoded with `rawurlencode()`, and all other characters will be left alone.

In addition, I added tests for the `UrlHelper.formatPath()` method. Test coverage in this library is still wildly insufficient, but this PR at least makes things better than they were yesterday.

Note: this PR should fix #28.

### CODE REVIEW

File: tests/Imgix/Tests/UrlHelperTest.php [hunk 1]
```diff
@@ -4,6 +4,65 @@
...
+
+        $this->assertEquals($uh->formatPath($path), "/http%3A%2F%2Fmywebsite.com%2Fimages%2Fdog.jpg");
+    }
+
+    public function testHelperFormatPathWithFullUrlWithEncodedCharacters() {
+        $path = "http://mywebsite.com/images/p%C3%BCg.jpg";
+        $uh = new URLHelper("test.imgix.net", $path);
+
+        // The pre-encoded characters should now be *double* encoded
+        $this->assertEquals($uh->formatPath($path), "/http%3A%2F%2Fmywebsite.com%2Fimages%2Fp%25C3%25BCg.jpg");
```
Comment (nathan-heskia) [inline tests/Imgix/Tests/UrlHelperTest.php]: Why would we want to encode an already encoded path?

File: src/Imgix/UrlHelper.php [hunk 2]
```diff
@@ -10,23 +10,34 @@ class UrlHelper {
     private $signKey;
     private $params;
 
-    public function __construct($domain, $path, $scheme = "http", $signKey = "", $params = array(), $rawEncodePath = false) {
+    public function __construct($domain, $path, $scheme = "http", $signKey = "", $params = array()) {
```
Comment (nathan-heskia) [inline src/Imgix/UrlHelper.php]: I think this changes means you can also delete `$rawEncodePath` from both the signature and the call to this constructor in `UrlBuilder`'s `createURL` method.

File: src/Imgix/UrlHelper.php [hunk 3]
```diff
@@ -10,23 +10,34 @@ class UrlHelper {
...
             return '/';
 
-        if (0 === strpos($path, "http"))
-            $path = $rawUrlEncode ? rawurlencode($path) : urlencode($path);
+        // Strip leading slash first (we'll re-add after encoding)
+        $path = preg_replace("/^\//", "", $path);
 
-        $path = ($path[0] === '/' ? '' : '/') . $path;
-        return $path;
+        if (preg_match("/^https?:\/\//", $path)) {
```
Comment (nathan-heskia) [inline src/Imgix/UrlHelper.php]: Why do you only match on `https`? Could someone also provide a path with `http`?

Comment (jayeb) [reply src/Imgix/UrlHelper.php]: This regex matches both--the `?` following the `s` makes it an optional character.

File: tests/Imgix/Tests/UrlHelperTest.php (hunk 1 above)
Comment (jayeb) [reply tests/Imgix/Tests/UrlHelperTest.php]: It's basically impossible to detect whether the path we're given has been pre-encoded or not, so we need to assume all paths are given to us *unencoded* and encode them blindly. This test just makes sure that, in the rare event that someone chooses to pass in a pre-encoded path, it gets double-encoded as expected. More of a safeguard to make sure we don't break this edge-case behavior in the future by accident.

File: src/Imgix/UrlHelper.php (hunk 2 above)
Comment (jayeb) [reply src/Imgix/UrlHelper.php]: Good catch, thanks

File: src/Imgix/UrlHelper.php (hunk 3 above)
Comment (nathan-heskia) [reply src/Imgix/UrlHelper.php]: Ah, okay! Got it.

File: tests/Imgix/Tests/UrlHelperTest.php (hunk 1 above)
Comment (nathan-heskia) [reply tests/Imgix/Tests/UrlHelperTest.php]: That makes sense. Thanks for clarifying.

File: src/Imgix/UrlHelper.php (hunk 3 above)
Comment (nathan-heskia) [reply src/Imgix/UrlHelper.php]: I approved the changes, but I think it would still work the same and be more readable to have the regex as `/^http(s)?:\/\//`. But I'll leave that up to you!
