### PR TITLE
fix: add domain validation at UrlBuilder initialization

### LINKED ISSUE #10: Validate and sanitize domain names upon initialization
One of our customers ran into an issue where they accidentally provided a path component to a domain name when initializing an `Imgix\UrlBuilder`.

We should validate and sanitize these, failing as early as possible if necessary.

### PR DESCRIPTION
**Pull request by sherwinski**
Adds a validation that will throw an error if a user attempts to initialize a new `UrlBuilder` object with an invalid domain.
The validation criteria is based off of the same regex used on [dashboard.imgix.com](https://dashboard.imgix.com)

Fixes #10

### CODE REVIEW

File: src/Imgix/UrlBuilder.php [hunk 1]
```diff
@@ -23,12 +23,27 @@ public function __construct($domains, $useHttps = false, $signKey = "", $shardSt
...
+
         $this->useHttps = $useHttps;
         $this->signKey = $signKey;
         $this->shardStrategy = $shardStrategy;
         $this->includeLibraryParam = $includeLibraryParam;
     }
 
+    private function validateDomain($domains) {
+        $DOMAIN_PATTERN = "/^(?:[a-z\d\-_]{1,62}\.){0,125}" .
+        "(?:[a-z\d](?:\-(?=\-*[a-z\d])|[a-z]|\d){0,62}\.)[a-z\d]{1,63}$/";
```
Comment (jayeb) [inline src/Imgix/UrlBuilder.php]: I think you should just put this all on one line, length-guidelines be damned. It's not like you're making it any more readable by splitting it between two.

File: src/Imgix/UrlBuilder.php [hunk 2]
```diff
@@ -23,12 +23,27 @@ public function __construct($domains, $useHttps = false, $signKey = "", $shardSt
...
+
+        foreach($domains as $key => $val) {
+            if(!preg_match($DOMAIN_PATTERN, $val)) {
+                throw new \InvalidArgumentException('Domains must be passed in as fully-qualified ' . 
+            'domain names and should not include a protocol or any path element, i.e. ' .
```
Comment (jayeb) [inline src/Imgix/UrlBuilder.php]: [nit] Indentation here.

File: src/Imgix/UrlBuilder.php (hunk 1 above)
Comment (sherwinski) [reply src/Imgix/UrlBuilder.php]: 🙃
